import { PropsWithChildren } from 'react'
import { Header, StoreProvider } from '@/components'
import '@/styles/globals.scss'
import styles from './layout.module.scss'

export const metadata = {
  title: 'Pokédex',
  description: 'Generated by create next app'
}

function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          <div className={styles.scroll}>
            <main>{children}</main>
            <footer className={styles.footer}>
              Make with <span>❤</span>
            </footer>
          </div>
        </StoreProvider>
      </body>
    </html>
  )
}

export default RootLayout
